config/routes.rb
Rails.application.routes.draw do
  resources :books
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
    # Presence
    validates :title, :author, :description, presence: true
    # Uniqueness
    validates :title, :description, uniqueness: true
    # Length
    validates :title, :author, length: { maximum: 100 }
    validates :description, length: { maximum: 100 }
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_controller.rb
class BookController < ApplicationController
    def index
        @books = Book.all
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :description)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
        if params[:query]
            @query = params[:query]
            @results = Entry.where("content LIKE ?", @query + "%")
                            .map { |entry| entry.content }
            @count = @results.length
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book/index.html.erb
<ol class="book-list">
    <% @books.each do |book| %>
        <li class="book-item">
            <span class="book-author">(<%= book.author %>)</span>
            <span class="book-title"><%= book.title %></span>
        </li>
    <% end %>
</ol>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>" class="book-item">
  <p class="book-title">
    <%= book.title %>
  </p>

  <p class="book-author">
    <%= book.author %>
  </p>

  <p class="book-description">
    <%= book.description %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book, class: "book-form") do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>
<div class="button blue">
  <%= link_to "Show this book", @book %>
</div>
<div class="button gray">
    <%= link_to "Back to books", books_path %>
</div>

<br>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>

<h1>Books</h1>
<div class="button blue">
  <%= link_to "New book", new_book_path %>
</div>
<br>

<div id="books">
  <% @books.each do |book| %>
    <%= link_to book, class: "book-link" do %>
      <%= render book %>
    <% end %>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<div class="button gray">
  <%= link_to "Back to books", books_path %>
</div>
<br>

<%= render "form", book: @book %>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>View Book</h1>
<div class="button gray">
    <%= link_to "Back to books", books_path %>
</div>

<br>

<%= render @book %>

<br>

<div class="button green">
  <%= link_to "Edit this book", edit_book_path(@book) %>
</div>
<div class="button red">
  <%= link_to "Delete this book", book_path(@book), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
  } %>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <p>© Test Tester</p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <h1>Book List</h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExerciseRandomizer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
    </header>
    <nav>
    </nav>
    <main>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/search/index.html.erb
<div class="search-container">
    <%= form_with url: root_url, method: :get do |form| %>
    <%= form.label :query, "Search for:", class: "search-label" %>
    <%= form.text_field :query, class: "search-input" %>
    <%= form.submit "Search", class: "search-button" %>
    <% end %>
</div>

<% if @query %>
    <div class="result-container">
        <p class="searched-query">Searched for "<%= @query %>", <%= @count %> Results:</p>
        <ol class="result-list">
            <% @results.each do |result| %>
                <li class="result-item"><%= result %></li>
            <% end %>
        </ol>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>